[package]
name = "pistachio"
version = "0.1.0"
edition = "2021"
description = "A Prometheus exporter designed for monitoring UPS devices using Network UPS Tools (NUT)."
license = "GPL-3.0-or-later"

[dependencies]
env_logger = "0.11.5"
log = "0.4.22"
prometheus_exporter = "0.8.5"
rups = "0.6.1"
